### ISSUE TITLE
v0.4.0 File to import not found or unreadable: ember-freestyle

### ISSUE THREAD

**Issue by jpsanantonio** [chrislopresto/ember-freestyle#115]
Everything's working fine in v0.2.14, however when I tried upgrading my project to use ember-freestyle@0.4.0 I get this error: 

```javascript
File: /Users/jayvics/Documents/workspace/prime/tmp/sass_compiler-input_base_path-YH6H5llX.tmp/app/styles/app.scss (15)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ember-freestyle.
Parent style sheet: /Users/jayvics/Documents/workspace/prime/tmp/sass_compiler-input_base_path-YH6H5llX.tmp/app/styles/app.scss
    at options.error (/Users/jayvics/Documents/workspace/prime/node_modules/node-sass/lib/index.js:291:26)

The broccoli plugin was instantiated at:
    at SassCompiler.Plugin (/Users/jayvics/Documents/workspace/prime/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/Users/jayvics/Documents/workspace/prime/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Users/jayvics/Documents/workspace/prime/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /Users/jayvics/Documents/workspace/prime/lib/css/plugin.js:146:12
    at Array.map (native)
    at CSSPlugin.sassTree (/Users/jayvics/Documents/workspace/prime/lib/css/plugin.js:143:34)
    at CSSPlugin.toTree (/Users/jayvics/Documents/workspace/prime/lib/css/plugin.js:173:19)
    at /Users/jayvics/Documents/workspace/prime/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/jayvics/Documents/workspace/prime/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
```

**Comment by chrislopresto** [comment]
@jpsanantonio Sorry about that. You had perfectly unlucky timing. That's a bug that should be fixed in 0.4.1 Can you try upgrading and let me know how it goes?

Thanks!

**Comment by jpsanantonio** [comment]
@chrislopresto Just upgraded to 0.4.1 but it's still not working.

**Comment by chrislopresto** [comment]
@jpsanantonio Oh, sorry. I just read the error message more closely. You also need to remove `@import 'ember-freestyle';' from your app.scss file.

I just updated the [v0.4.0 release notes](https://github.com/chrislopresto/ember-freestyle/releases/tag/v0.4.0) accordingly.

**Comment by jpsanantonio** [comment]
@chrislopresto Nice! It's now working perfectly. Thanks!

**Comment by chrislopresto** [comment]
Excellent! Let me know if you have any questions about the release. Closing this.
